language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: fMFA79yuHN7kp7nnjSX3QY7hq1u9zfursgKDJHvYN0EKKldAZBeMJTGKz3Ojxfh4Fx5o9+DC82AYyXVFQqIeli66zmUdTOFveByGzmdEgwUFI1ppfWHfL6gjHqccB4WvmZ5v6zaB6VkaXmQAc7vB9G4g81bJJCPgeCbYM1uvuEaynY0UUzkBLVI1YGhcP6z7LbV2Lp/SVRppNjZsaTVqpshKM+h5vvrRXfu4zgrg0dztGGSjWp7bJSE58wu6eEgtNWZIpUnfk2fURfYAKDMETSVLplZy9HlcHThYH6nlnXx3giGXqI+e1RgfnF5Iec1f7vi2b0OFS/5sLjMIuKv9uJx+JvWm/teFNZ2qSf7kI8Wq8xPstzzwvYf1M0m5DzENulmVrvRHTjgiAPme1I1SEQ3RBUefUrSOpmlU5SQjg83Rhl7IuE+sCFRmaN1qgcM6A53aCGp2UY8qqqaTmalANu15+qmvkxqzxy6TyfVmBC0suGRPj0DXMJ8d2+AaADzl6nIY6TZDVIxqhARPkBiS1HgyFx09NYz/a8jgapMv648PSzzqxzTDG770WFmmflC70keo0dQEhXTM+nMZWz1KfuLqtHeM2LPkUN5gHxPo4PyDCS+qleFxvGLHariv1jtkxb/g9AWgDejjt+szD5AErpzub1iccDYz6Kuv4tB5lBE=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
