language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: X0n8tvg9poH+NVIdWyrXjYmJfFtVhQp8LLRusBVR3kajGblhwapxfJQyjMcfb8XG8OdlXctYUHZ0P1/RIs2Wv7BUE6LA8vwuxG3yrr6QKCDcKzyX6eQgqLnDs5UGQvCtlPDrRIgzAzxJBZLqDS0lnM/hh12xn0/PSC1wNWqhPjufCwSXMogyvRadZxgTqlr9ZizZ/C4oqE0OYgVUhA+T1yCMoUZsBkkSZsJ3JV0W5+wn+mfgP6M+/bakFuKCqEaEz3RXBE569kmThDFz+sQX20qC25v45QlUkcVZrP6nr13ceSLUUXFJb1sNaYh+olOzOUxkW045L+nZz+4x5R8kEu8qpF9hCdTaWTpqtfzvpEq18PZ5bB4YUT7LY4JGzg6f2ODp42KZfR4hbPuZP9EnDTOZ27aSCpjLTrUk85Pc8fjdQ/hYr5xZg+SNuymEytCht24Z31l5/y49SHlY7ckiUdTS4ncT6vGtI4uTait28grVw7yuHhlcLrxwzgV2UDkP1ME0LRi2k8F0kqjuzTVdyMK8Tk0tzyI1QXdt041ELH7BIuC7QUETXgDXmZuf8rOZz/sKyb3wYW+2WrQYSIgtmpRJSymd8SquD7WfxGUVocoJ+MxnQKY5A1Pq3V0U+rs3Payjf5B0pzBAXkKgfetYcIYuKpjQbpoQOJwW/M3gjmQ=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
