language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: B4LrJ70WShjVF9D2HRoMuFX8E9iX3GkNXfuG1tiRKPntogVTsTMUQFquwb2CW/F6PYltcbd4/J44pNLggu7N5TjwdQr5A+qHiPuIYVcCcatgd1kQkrEe32+2XuHldMiZOWx+/hXS1mfCLaXjoO0SWEdY2YryGdA1jMO7nCuS0GlYHp5ipXgi18BKuTrdtBCqkfgNrsG7EN519ybz6RglV/cRAD46WEs5vpa2bQsZh0WGCau1/DRHFPOwpjCEbid3vS4VlYwkIxxmt4Dv+imAaQvTXLVWup3DTlpb0umigiun8bsAHQFLI8ELodH5g5LPpW01gkdYVzShIi1YySjX00+o+ALozXn9u6s9zBUkExJ1vz7mMhUBStoDuRexejbSiYkfgJGBf2UYWHJvtN/SSMsA3XKx/Z/5pI8u+TN2hIFbmlbaLl6UpJjI9InrTWasiQm9OSBsDO7dgcinA3gtQeh2bCe2FqSqreSHiK9O3Zrm1me6iMmIVDKDwBi9/qCfYoYoq6dlEOpHSOWWtQ0NtAzj3Vz8L4VPGhmW5ySqkcNsm9KnTtlQmTEt85CemHMBNd8p+g4FcMwNNSPr7JCh17gP3L++O6RrVr7siCnkH+Q+H/0dj2SrijEkN/3mnecYYftq9slvRkcYCnqOg5PvmtbIn1H9PmqRDO2Wn+jpWeQ=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
