language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: JIyMgUtgXhzSWpsUv7AN+GTpQjZuY3/NEJsDkRWc28ymOR9R4a7KJ7KlC7Fe95SYgXDkXqOS0MBRVzYgCikDDNAZCB4YqxZ/DjZpVyLOQKT6kGvEQMkIXjw8vAj/H4G3auMPPJDlbLU5H08ul9+TZMh8iAk2w10ZYc9mTU0uxjIKuKc2d370C/Q1ArJ87BW8dyPcZwzPG4Td4b8VpkJ1x5ifW4BhB/7p+2nb9wF+bKOOUmYwgLyfAwdUYNMt/YjQ7KTtVCnfazUtkRDopZYwQP9aBFIX0fdulPpeLbNF/1cc2mRdWBVNFpjimqX/Oj+iX9sUYwpyzNpttnEBylD66A/v576arQnbPvQhcmkjvkJvZSDeDvpJDrMuP9MxhX1CAv0xrlcI9+QBSWCmIhCdDSm2qn3GMNwO8JqeyES+n4GanslWSq6dMvUawm7RBqkhjusRxkZ92KpVXZDyizHdCoGj7C9ti7dUTbIb3evh3u8DxbC95FjIRgZVirbteJcv4H/ObNGwK7xRew0rEusc4pKC94Jopn+krbmoDnle53SCHXuhTy+Brh97SS98hCnzfsdCwuzS7r/AG1+p2pQsC/bfo8m7ISiYVNQLK5gLKrnfoIbwyfLDaBjQm6jBQmIuduwgqIWI4ZcAt+DuFNzSbMGs/wvB0XVgXcNR9MyJ+sY=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
    branch: master
