language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: bhvlZIWMBQUCgpiGTsS3vK6XEzmbEu6LJteUkKwNZWdpsUrm2BrzhuBCq6kV48Nvo70860YSqJvY6fF9qnAoN7N7Fm7IHG/VUnnUknjSvPaok7JTjrQxN0w/drU13Z6yOV5lgbQjWflvDKfT5bcCDgPszkshOS9kR3QDF9CUtLbqMQEEMDin+xuREDi/8fX9l6iq/E3DE8ef1ID/pNplNiZ0b548nfRh3P/u6Hcnims3jR2jvbgsrDHa/vnUHEavWGmCRc2AOcHEi9uqQU9EaINmmaiemA1Wni1eDwB1h97oRtco9gjq7O7p7aomqwXpqgpzAyjSmeGRawq/TaITY3SvI7Sh0o/H7ppH1KNplaPYWjQ7jkz4UEljgFu7uMB5o3NB/0pPc6HgE6s+5I+8tR+b2jk+r07AF8GkPAQ8wRq3vl3ZIbzCBxuXLcz1F1jKaOv8H6RVjevvtLngy1qXcRHKP/sPOROs1zktfp3eGBQXmzlxyFHSt4Olc9PuLgplxdxRQa32uh7d8xj+CnNegju/m4G9Wf8QK1F/9wvq2iTjEu9LlEcHrfxa4NwgoWcEt6VH4xX1tEhcUKUNj8Una+oEMvz3tsIuecpyhdWW4gj16ORKDoF31KStiKDy841PrULt5KbI+51LdD6fuO9S3n9EKhLBlbkMCNckYZ1DOrk=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
