language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: bPt7C0lS92Mrp9+IpVkb3c6CaERjseV2GIyyq0Ly6HtQ8gjUIRcaJpl4X5BJtxsS4v3f/mTOwnVZFWmdNTQDrCmFjXZZ07Cg3EZspQGXDEap0dEYdTT4qMOzePGSPl2k6v9lKLT2gG5hCbOMLfBTr+EJLAVo25Bl5xB+cdUi+PggdnqMfe6p8Wet56nn6dtI5uyOBZXhWNajQV9Bd/guVp2ML58ZJ4iMO+WHJVT5qbXWH/Rl2TLlTD9QVI1ASEr7CnHNR+1Tvg5roW7G5S3XEFbdmA0gutR7RwAOo+zP0j4JwZlXjob0WZU6AkpN8+Yc0aZk9Elw1Yk8Yi+X9gDvx3/RLSGbOssReHi1a3EC8rJLzeMoViCNMPv0FmqcZJbKM7GcLrGBFFRF0j31HvusKJ0JGA1625XLwpqVo4jBrOJLSrQSsoV9/eE+64nPUouHdqTl/NGSn+RIX/kQ+6WWPivhI7N1tpTDP+XIirtIzBqp8LrXPb0o7x5ucP6TQyYCvVHK1V1+mQi4M7RZEY7QiX0ilmj5EWtbn5ZLkZQPOk1m11LzhHFLzEZ9ri+CBfQIFlghyUNeoazxfkdywNc42zC1WOfoISN/MekEg3+oOCEX1RHWVotEt8PPKZOEk6xXi6KsmkIz+xJbaLeyMP+ppaSPL2H58mMvv4VaT6Rd7bw=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
