language: node_js
node_js:
- 10.9.0
script:
- yarn run lint
- yarn run test
deploy:
  provider: heroku
  api_key:
    secure: UhmSV6Uh2bfjNGagTAiBZiac821ND/yebjHCZY+T+877CO22qNjVwy0A3iM4UJaY7TjHjfOERN15J9X4NcmRs+gkqwhKP4ZDU9aKk3RtQ3jN3RCJyKROV56FfwhAeoizUeTw6cLHLMUpBuMrFK+ojHzp1lMBm3RFnOBEjd2Sl5g8m5ghogddZHPP1220ZKJwwoBaUDRYc+GTTdW65A52NVGhTnUzuVN+KRPt3dhbPOd4O188VKyrW163Glm0jK1MVxy00WspzHYaQPwIKcsJThGpeGK+n6ZIx2Fqk2RRcoU875bQb+lTaCxxA2OmxN9zj4rm5aZbbdOlD6xMfUjSzLLV2p/NvFmwd4xhIOgjVBk5z5bL8Kg1pLvLoCbetRwNHNlD+IFF8KRL6qZBfM6wHcAf2kfhaX1LQiZ2bYN/Qypu9S4zL4hKSKcY7RfO5Jl6X9wc0nBFGGtwzXoH2QOd/kxAZsJTmFCCA2pSzJYxxzjPfX91p5DS0fws/7TUhODp8Gjc2XqBEDox1cpK+b7Q2UQs2lpBVGHvS5TuupW/7xeKHirXCc2LjNFpnqNuZ3QlJQZdOnKHIciCU3hkD1FBlaBLfvl/sIkh5WGTp2rzSJ9ukuol2Mrlv66Y6jXUdyBvcVqgT8OkfSAwxcgR/y3TkSgPz83YWqAiVyYRynwJs1g=
  app: nyt-react-3212
  on:
    repo: t-d-o-g/nyt-react
